#!/usr/bin/env sh
. "$(dirname -- "$0")/_/h"

if command -v nvm >/dev/null 2>&1; then
    export NVM_DIR="${NVM_DIR:-$HOME/.nvm}"
    # shellcheck disable=SC1091
    . "$NVM_DIR/nvm.sh"
    nvm use >/dev/null
fi

if [ -f package.json ]; then
    npm run test --if-present
fi
