#!/usr/bin/env sh
. "$(dirname -- "$0")/_/h"

if command -v nvm >/dev/null 2>&1; then
    export NVM_DIR="${NVM_DIR:-$HOME/.nvm}"
    . "$NVM_DIR/nvm.sh"
    nvm use >/dev/null
fi

npm run lint:staged
